### ISSUE TITLE
Document how to read a dump from a local file

### ISSUE THREAD

**Issue by fenopa** [macbre/mediawiki-dump#210]
not possible?

**Comment by matkoniecz** [comment]
It would be great to have such option - it would also allow reading from other wikis. Such as say OSM Wiki, see https://wiki.openstreetmap.org/wiki/Wiki#Wiki_Dumps_.2F_Export

**Comment by macbre** [comment]
Let's introduce a new `MediaWikiDumpFile` class:

```
from mediawiki_dump.dumps import MediaWikiDumpFile
```

**Comment by macbre** [comment]
Actually, it's already there :-) The `LocalFileDump` class is your friend here. I'll update the README to describe that case as well.

https://github.com/macbre/mediawiki-dump/blob/master/mediawiki_dump/dumps.py#L181-L196

**Comment by macbre** [comment]
@matkoniecz, can you check the following code with the OSM wiki dump that you've mentioned?

```python
    dump = LocalWikipediaDump(dump_file="path/to/osm.dump.xml.bz2")
    reader = DumpReader()

    pages = reader.read(dump)
```

**Comment by matkoniecz** [comment]
@macbre Do you have known example of such download working? Maybe I should download small wikipedia and try is it loadable from file for me?

Is it working for you?

**Comment by macbre** [comment]
> Is it working for you?

It does, see #226. Please make sure that the XML file you're reading is not compressed.
